version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=password123
      - REDIS_AOF_ENABLED=no
      - REDIS_PORT_NUMBER=6379
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/app?sslmode=disable
      - GIN_MODE=release
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait_for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "api"