// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Username         string      `json:"username"`
	Password         string      `json:"password"`
	Name             string      `json:"name"`
	Surname          string      `json:"surname"`
	Enabled          bool        `json:"enabled"`
	Role             pgtype.Int4 `json:"role"`
	Email            string      `json:"email"`
	PasswordChangeAt time.Time   `json:"password_change_at"`
	CreatedAt        time.Time   `json:"created_at"`
	IsEmailVerified  bool        `json:"is_email_verified"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
